spring:
  datasource:
    url: jdbc:mysql://mydb999.cvq0mwsg6he7.ap-south-1.rds.amazonaws.com:3306/courses
    username: admin
    password: Harish999
  jpa:
    hibernate:
     ddl-auto: update
     show-sql: true

server:
  port: 5000